#include "hal_data.h"
#include "threads_sync_own.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
        ThreadsSync_Open();
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif

/******************************************************************************************/
/* callback function for the S1 push button; writes the new level to LED2 and sends it    */
/* through the USB to the PC                                                              */
/******************************************************************************************/
void external_irq_button_callback(external_irq_callback_args_t *p_args)
{
    /* Not currently using p_args */
    FSP_PARAMETER_NOT_USED(p_args);
    //extern bsp_leds_t g_bsp_leds;
    //bsp_leds_t Leds = g_bsp_leds;

    //s1_pressed = true;
    g_ioport.p_api->pinWrite (&g_ioport_ctrl, BSP_IO_PORT_10_PIN_08 , true);

    //R_USB_Write (&g_basic0_ctrl, (uint8_t*) send_str, ((uint32_t) strlen (send_str)), (uint8_t) g_usb_class_type);
}

void led_on(void)
{
    g_ioport.p_api->pinWrite( g_ioport.p_ctrl, BSP_IO_PORT_10_PIN_08, 0  );
}

void led_off(void)
{
    g_ioport.p_api->pinWrite( g_ioport.p_ctrl, BSP_IO_PORT_10_PIN_08, 1  );
}

void led_toggle(void)
{
    static uint8_t led_status = 1;
#if 1
    if (led_status == 0)
    {
        led_status = 1;
        led_on();
    }
    else
    {
        led_status = 0;
        led_off();
    }
#endif
}

void pin_toggle(void)
{
    static uint8_t pin_status = 0;
#if 0
    if (pin_status == 0)
    {
        ASSERT( g_ioport.p_api->pinWrite( g_ioport.p_ctrl, BSP_IO_PORT_02_PIN_05, 1  ) == FSP_SUCCESS);
        pin_status = 1;
    }
    else
    {
        pin_status = 0;
        ASSERT( g_ioport.p_api->pinWrite( g_ioport.p_ctrl, BSP_IO_PORT_02_PIN_05, 0  ) == FSP_SUCCESS);
    }
#endif
}

/******************************************************************************************/
/* callback function for the S1 push button; writes the new level to LED2 and sends it    */
/* through the USB to the PC                                                              */
/******************************************************************************************/

void button_init(void)
{
#if 1
    g_external_irq9.p_api->open(g_external_irq9.p_ctrl, g_external_irq9.p_cfg);
    g_external_irq9.p_api->enable(g_external_irq9.p_ctrl);
#endif
}
